export const routes = {
    LOGIN: "/login",
    SIGNUP: "/signup",
    FEED: "/feed",
    EXPLORE: "/explore",
    ORGANIZATION: "/organization",
    FORGOT_PASSWORD: "/forgot-password",
    RESET_PASSWORD: "/reset-password",
    PROFILE: "/profile",
    SETTINGS: "/settings",
    LOGOUT: "/logout",
    HOME: "/",
    NOT_FOUND: "/404",
    SERVER_ERROR: "/500",
    SERVICES: "/services",
    INTERNAL_ERROR: "/500",
    UNAUTHORIZED: "/401",
    FORBIDDEN: "/403",
    BAD_REQUEST: "/400",
    CONTACT: "/contact",
    ABOUT: "/about",
    TERMS: "/terms",
    PRIVACY: "/privacy",
    HELP: "/help",
    SUPPORT: "/support",
    BLOG: "/blog",
    PRESS: "/press",
    CAREERS: "/careers",
    OTHER_PROFILE: "/other-profile/:username",
  }
  